server:
    port: 8080

spring:
    profiles: dev

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003



# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: com.github.fromi.tictactoeonline
      domain: com.github.fromi.tictactoeonline.domain
      restdto: com.github.fromi.tictactoeonline.web.rest.dto
    watchdir:
      - target/classes
